### PR TITLE
Add C++ unit testing

### PR DESCRIPTION
**Pull request by hhenry01**
### Description

I added some extra unit testing tools in this PR. 
image
Right clicking the green check also gives a context menu to run and debug individual tests which is nice.

### Verification

-

### CODE REVIEW

**Review by patrick-5546 — COMMENTED** [review]
Let's put this on hold until I upgrade the docker image to the latest Ubuntu and ROS LTS distributions. Perhaps this will resolve the missing file issue you discovered.

**Comment by patrick-5546** [comment]
- Merge with main once #77 is merged in

**Review by patrick-5546 — COMMENTED** [review]
Reading over your PR I saw you tried to debug the ROS launch launch config. It should work in main now with ROS humble, but lmk if that isn't the case.

The unit testing tools look great. There is something similar that I configured for Python, so it's great that we can achieve feature parity.

lmk if you need help merging with main. You may find it easier to add your changes to a new branch rather than trying to resolve the merge conflicts.

**Comment by hhenry01** [comment]
I rebased this branch and it's just for the unit testing extension now.

**Review by patrick-5546 — APPROVED** [review]
Verified that it works on my machine, if there's nothing else that you want to do in this PR feel free to merge

**Review by patrick-5546 — APPROVED** [review]

**Pull request merged**
