### PR TITLE
Website infrastructure updates

### PR DESCRIPTION
**Pull request by jahn18**
### Description
- ~~Port forward the mongodb container~~
- Fix updating dependencies
- Add cucumber.js extension for website tests

### Verification

- Run the `website` and `db` containers. 
- Ensure that `MONGODB_URI` is set to `mongodb://localhost:27017` within `.env.local` in the website repo.  
- Go to the URL `http://localhost:3005/api/gps`. You should expect the following response `{success: true, data: [ ]}` if the website connected to the database successfully. 
### Resources

-

### CODE REVIEW

**Review by patrick-5546 — COMMENTED** [review]
Can you add to the verification section how I could check if it works as intended?

**Comment by jahn18** [comment]
> Can you add to the verification section how I could check if it works as intended?

Done

**Review by patrick-5546 — COMMENTED** [review]
As we discussed, will approve once you revert the port forwarding changes and add the website test extension

**Comment by jahn18** [comment]
@patrick-5546 Should be good to go now.

**Review by patrick-5546 — APPROVED** [review]

**Pull request merged**
