### PR TITLE
Fix create new package with a node tasks

### PR DESCRIPTION
**Pull request by patrick-5546**
To try out this fix:
1. Checkout to this branch: `git switch patrick-5546/fix-tasks`
2. Open the workspace
    1. Open `.devcontainer/config/sailbot_workspace.code-workspace` in VS Code
    2. Click "Open Workspace"
3. Try running the task

### CODE REVIEW

**Comment by colinli02** [comment]
Your fix works, however I have to manually add the lines of code that you added:
```
},
			{
			"id": "node",
			"type": "promptString",
			"description": "Node name"
			}
```
into the autogenerated tasks.json file in ```sailbot_workspace\.vscode``` folder. I assume tasks.json is auto generated since its not in the github .vscode folder originally (on github) and somewhere along the steps to set up the workspace it was autogenerated.

The modificiations in sailbot_workspace.code-workspace that you made don't seem to automatically modify tasks.json. I'm not sure if this is a configuration I messed up or something, but running tasks from quick open e.g. "task setup" seems to use the tasks.json folder instead of sailbot_workspace.code. I'm unsure if this is the intended behavior. I am also unable to find out what causes tasks.json to be auto-generated or automatically modified.

The reason I am bringing this up is because if there is a case where there is lots of code changes regarding tasks in the sailbot_workspace.code file, it might take a lot of time to manually change tasks.json.

**Comment by patrick-5546** [comment]
You have to open the workspace in VS Code before you can use the tasks (I migrated them to the workspace file). See the instructions that I put in the PR description

**Comment by colinli02** [comment]
Oh that seems to work. I'm inexperienced and vscode and didn't know opening the workspace was a literal feature under file, and misunderstood that as to just "opening" the code in the editor.

Problem seems to be resolved.

**Review by colinli02 — APPROVED** [review]
After opening the workspace, the task "new ament_cmake package with a node" works as expected.

**Pull request merged**
