### PR TITLE
Add timeout to each CI test

### PR DESCRIPTION
**Pull request by patrick-5546**
### Description
Add a timeout for each job, because if something runs for much longer than usual there's probably something wrong.

@hhenry01 do these timeouts look reasonable to you?

### Resources
- https://stackoverflow.com/a/59076067

### CODE REVIEW

**Comment by hhenry01** [comment]
Is that enough time for build-images? Prebase takes like 3 hours, is it not included in the timeout?

**Comment by patrick-5546** [comment]
> Is that enough time for build-images? Prebase takes like 3 hours, is it not included in the timeout?

Build images only builds base and dev. For pre-base you have to build locally and push yourself.

**Comment by hhenry01** [comment]
> > Is that enough time for build-images? Prebase takes like 3 hours, is it not included in the timeout?
> 
> Build images only builds base and dev. For pre-base you have to build locally and push yourself.

In that case LGTM. I just need to make sure clang-tidy doesn't balloon out of control.

**Review by hhenry01 — APPROVED** [review]

**Comment by patrick-5546** [comment]
It currently takes ~20 minutes to build base and dev in CI: https://github.com/UBCSailbot/sailbot_workspace/actions/workflows/build-images.yml

Although we technically have unlimited minutes for GitHub actions, that may change in the future and the time saved > convenience of CI in this case IMO

**Pull request merged**
