### PR TITLE
Use buildx to build multi-arch images

### LINKED ISSUE #31: Support ARM computers
Push ARM versions of the docker images so that this workspace can run natively on ARM computers like the M1 Macbooks.

### Resources
- https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/

### PR DESCRIPTION
**Pull request by patrick-5546**
### Description

- Resolves #31

These multi-arch images will be for amd64 (x86) and arm64v8 (arm) devices:
- x86
    - Personal devices like Dell XPS: development and testing in dev container image
- ARM
    - Raspberry Pi 4: testing and production in base image
    - Personal devices like ARM MacBook: development and testing in dev container image

### To Do
- [x] Clean up `build-base.sh`
- [x] Update OMPL commit in `base.Dockerfile` (or create an issue for this)
- [x] Dev image uses multi-arch base image 
- [x] Make git delta install multi-arch or remove
- [x] Update build dev image workflow
    - [x] ~Does not publish `unknown/unknown` os/arch~ add to known issues
- [x] ~Update tests workflow to run on x86 AND arm ubuntu~ create a separate issue for this based on https://github.com/UBCSailbot/sailbot_workspace/pull/79#issuecomment-1399197944
- [x] Dev container uses multi-arch dev image
    - [x] Passes x86 CI
    - [x] Works on x86 laptop
    - [x] Works on ARM laptop
- [x] `git merge origin/main` once #85 is merged
- [x] Document how to build and use base and dev image based on https://github.com/UBCSailbot/sailbot_workspace/tree/raye/.devcontainer
- [x] Create a separate issue for running base image on x86 laptop and RPi based on https://github.com/UBCSailbot/sailbot_workspace/pull/79#issuecomment-1399197944

### Verification

- [x] Run dev container on x86 laptop
- [x] Run dev container on arm macbook
- [x] CI passes

### CODE REVIEW

**Comment by patrick-5546** [comment]
Building the base image using buildx reduced its size from 2.5GB to 1.5GB

**Comment by patrick-5546** [comment]
@hhenry01 Can't compile network_systems on ARM:
```
Building Network Systems with build type 'RelWithDebInfo' and flags: '-O2 -g -DNDEBUG -std=c++20 -Wall -Wextra -Wpedantic -Werror -Wno-unused-parameter -pthread'
gmake[2]: *** No rule to make target '/usr/lib/x86_64-linux-gnu/libgtest.a', needed by 'projects/example/test_example'.  Stop.
gmake[2]: *** Waiting for unfinished jobs....
gmake[1]: *** [CMakeFiles/Makefile2:282: projects/example/CMakeFiles/test_example.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
gmake: *** [Makefile:146: all] Error 2
```

**Comment by patrick-5546** [comment]
Planning to explore several options for running tests on both the amd64 and arm64 variants of docker image:
- https://docs.github.com/en/actions/hosting-your-own-runners/adding-self-hosted-runners
    - Use Raspberry Pi as self-hosted runner
- https://github.com/marketplace/actions/run-on-architecture
    - Does not currently support x86 arch, but this is planned
- Manually specifying which version of the container to use?
    - Is this possible?
    - How to run arm container on x86 machine?
         - How much slower is it?

**Comment by hhenry01** [comment]
> @hhenry01 Can't compile network_systems on ARM:
> 
> ```
> Building Network Systems with build type 'RelWithDebInfo' and flags: '-O2 -g -DNDEBUG -std=c++20 -Wall -Wextra -Wpedantic -Werror -Wno-unused-parameter -pthread'
> gmake[2]: *** No rule to make target '/usr/lib/x86_64-linux-gnu/libgtest.a', needed by 'projects/example/test_example'.  Stop.
> gmake[2]: *** Waiting for unfinished jobs....
> gmake[1]: *** [CMakeFiles/Makefile2:282: projects/example/CMakeFiles/test_example.dir/all] Error 2
> gmake[1]: *** Waiting for unfinished jobs....
> gmake: *** [Makefile:146: all] Error 2
> ```

Resolving with https://github.com/UBCSailbot/network_systems/pull/12

**Pull request merged**
